import './globals.css'
import type { Metadata } from 'next'
import { Inter,Poppins } from 'next/font/google'
import Provider from './Provider';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
      <body className={poppins.className} style={{overflow:"hidden"}}>{children}</body>
      </Provider>
    </html>
  )
}
